apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.env.BETTER_AUTH_SECRET }}
  BETTER_AUTH_SECRET: {{ .Values.env.BETTER_AUTH_SECRET | b64enc | quote }}
  {{- end }}
  {{- if .Values.env.DATABASE_URL }}
  DATABASE_URL: {{ .Values.env.DATABASE_URL | b64enc | quote }}
  {{- end }}
